# Generated by Django 2.1 on 2018-08-30 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadioFrequencyRelay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('code_on', models.IntegerField()),
                ('code_off', models.IntegerField()),
                ('protocol', models.IntegerField()),
                ('pulse', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='radiofrequencyrelay',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistant.Room'),
        ),
    ]
